apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-db
  labels:
    app: drupal-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-db
  template:
    metadata:
      labels:
        app: drupal-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root_password
        - name: MYSQL_DATABASE
          value: drupal
        - name: MYSQL_USER
          value: drupal
        - name: MYSQL_PASSWORD
          value: drupal_password
        volumeMounts:
        - name: drupal-db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: drupal-db-data
        persistentVolumeClaim:
          claimName: drupal-db-pvc