apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 6
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:10.0-apache
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_DATABASE
          value: drupal
        - name: MYSQL_USER
          value: drupal
        - name: MYSQL_PASSWORD
          value: drupal_password
        - name: MYSQL_HOST
          value: drupal-db
        volumeMounts:
        - name: drupal-data
          mountPath: /var/www/html/sites/default/files
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - |
                if [ ! -f /var/www/html/sites/default/settings.php ]; then
                  cp /var/www/html/sites/default/default.settings.php /var/www/html/sites/default/settings.php
                  chmod 666 /var/www/html/sites/default/settings.php
                  mkdir -p /var/www/html/sites/default/files
                  chmod 777 /var/www/html/sites/default/files
                fi
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-pvc