apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 6
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      initContainers:
      - name: drupal-installer
        image: drupal:10.0
        command: ["/bin/bash", "/scripts/install.sh"]
        volumeMounts:
        - name: install-script
          mountPath: /scripts
        - name: drupal-data
          mountPath: /var/www/html/sites/default/files
      containers:
      - name: drupal
        image: drupal:10.0
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_DATABASE
          value: drupal
        - name: MYSQL_USER
          value: drupal
        - name: MYSQL_PASSWORD
          value: drupal_password
        - name: MYSQL_HOST
          value: drupal-db
        volumeMounts:
        - name: drupal-data
          mountPath: /var/www/html/sites/default/files
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-pvc
      - name: install-script
        configMap:
          name: drupal-autoinstall
          defaultMode: 0755