apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 6
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      # Container de initializare
      initContainers:
      - name: init-drupal-config
        image: busybox:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          cd /drupal-data
          mkdir -p sites/default
          
          # Descarca direct fisierul default.settings.php
          if [ ! -f sites/default/default.settings.php ]; then
            echo "Downloading default.settings.php..."
            wget -q -O sites/default/default.settings.php https://raw.githubusercontent.com/drupal/drupal/10.0.x/sites/default/default.settings.php || \
            curl -s -o sites/default/default.settings.php https://raw.githubusercontent.com/drupal/drupal/10.0.x/sites/default/default.settings.php
          fi
          
          # Copiaza settings.php
          cp sites/default/default.settings.php sites/default/settings.php
          
          # Creeaza directorul files
          mkdir -p sites/default/files
          
          # Seteaza permisiuni
          chmod 777 sites/default
          chmod 666 sites/default/settings.php
          chmod 777 sites/default/files
          
          echo "Drupal configuration files created successfully"
        volumeMounts:
        - name: drupal-data
          mountPath: /drupal-data
      containers:
      - name: drupal
        image: drupal:10.0
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_DATABASE
          value: drupal
        - name: MYSQL_USER
          value: drupal
        - name: MYSQL_PASSWORD
          value: drupal_password
        - name: MYSQL_HOST
          value: drupal-db
        volumeMounts:
        - name: drupal-data
          mountPath: /var/www/html/sites
      volumes:
      - name: drupal-data
        persistentVolumeClaim:
          claimName: drupal-pvc