apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 6
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
        - name: drupal
          image: localhost:32000/custom-drupal:latest
          ports:
            - containerPort: 80
          env:
            - name: DRUPAL_DATABASE_HOST
              value: "drupal-db"
            - name: DRUPAL_DATABASE_PORT
              value: "3306"
            - name: DRUPAL_DATABASE_NAME
              value: "drupal"
            - name: DRUPAL_DATABASE_USERNAME
              value: "drupal"
            - name: DRUPAL_DATABASE_PASSWORD
              value: "drupalpassword"
          volumeMounts:
            - name: drupal-files
              mountPath: /var/www/html/sites/default/files
          readinessProbe:
            httpGet:
              path: /core/install.php
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /core/install.php
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
      volumes:
        - name: drupal-files
          persistentVolumeClaim:
            claimName: drupal-files-pvc