apiVersion: v1
kind: Service
metadata:
  name: drupal-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.10
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: drupal

---
apiVersion: v1
kind: Service
metadata:
  name: chat-backend-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.11
  ports:
  - port: 88
    targetPort: 80
    protocol: TCP
  selector:
    app: chat-backend

---
apiVersion: v1
kind: Service
metadata:
  name: chat-frontend-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.12
  ports:
  - port: 90
    targetPort: 80
    protocol: TCP
  selector:
    app: chat-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: ai-backend-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.13
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: ai-backend

---
apiVersion: v1
kind: Service
metadata:
  name: ai-frontend-loadbalancer
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.14
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: ai-frontend