apiVersion: v1
kind: Service
metadata:
  name: chat-backend
spec:
  type: NodePort
  ports:
  - port: 88
    targetPort: 80  # Backend-ul asculta pe portul 80 intern
    nodePort: 30088  # Mapare pentru portul 88
  selector:
    app: chat-backend