apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
spec:
  type: NodePort
  ports:
  - port: 90
    targetPort: 80
    nodePort: 30090  # Mapare pentru portul 90
  selector:
    app: chat-frontend