apiVersion: v1
kind: Secret
metadata:
  name: azure-secrets
type: Opaque
data:
  storage-connection-string: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPXRlbWFibG9iO0FjY291bnRLZXk9YXFhblRpK2FHRldnOE1ldGMvQ3VKa0crYXBUOFdRZXZxMTJnOEVtWTVHVEVnNEdrOEloWjJrUjRBTXY2TVYwMUFSRFFKTU0rVmZ0citBU3RHdWg1dlE9PTtFbmRwb2ludFN1ZmZpeD1jb3JlLndpbmRvd3MubmV0
  ocr-api-key: QVJ4aVM1dW9pYUYwN01KSTF1dTRPeDl0ZU5kVUtpOU85WEVWZnhZaUJCWDdVazhCcHZRaEpRUUo5OUJFQUNHaHNsQlhKM3czQUFBRkFDT0dBWDBM
  sql-connection-string: U2VydmVyPXRjcDp0ZW1hLXNxbC5kYXRhYmFzZS53aW5kb3dzLm5ldCwxNDMzO0luaXRpYWwgQ2F0YWxvZz10ZW1hZGI7UGVyc2lzdCBTZWN1cml0eSBJbmZvPUZhbHNlO1VzZXIgSUQ9ZGJhZG1pbjtQYXNzd29yZD0mczlQLitmSCwqO0VXUUQ7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPUZhbHNlO0VuY3J5cHQ9VHJ1ZTtUcnVzdFNlcnZlckNlcnRpZmljYXRlPUZhbHNlO0Nvbm5lY3Rpb24gVGltZW91dD0zMDs=